
# @name get-prompts
GET https://upload-ai-1xt6.onrender.com/prompts

###

# @name upload-video
POST https://upload-ai-1xt6.onrender.com/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.mp3"
Content-Type: audio/mpeg

< ./1.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

# @name create-transcription
POST https://upload-ai-1xt6.onrender.com/videos/26beff36-37ed-4486-97af-b1a476d4d829/transcription
Content-Type: application/json

{
    "prompt": "caneta azul, tendo prazer com seus amigos"
}

###

# @name generate-ai-completion
POST https://upload-ai-1xt6.onrender.com/ai/complete
Content-Type: application/json

{
    "videoId": "26beff36-37ed-4486-97af-b1a476d4d829",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}